### PR TITLE
python3 and ldap3

### PR DESCRIPTION
**Pull request by ThePirateWhoSmellsOfSunflowers**
Hey, salut, ça va ?

As you know, I manage to find some time to properly migrate pywerview to python3 and change the ldap library.

This PR contains:
- early python3 commits from @mpgn, big thanks for kick starting this (I need to find time to listen to your podcast now, haha). This PR supersedes #34 
- various python3 fixes
- #35 from @99red. Thanks to you too, really cool and useful PR.
- a rewrite to change `impacket.ldap` to `ldap3` library, mostly because `ldap3` is a "perfect" implementation of LDAP RFCs.

I've tested the project against my own lab and during some assessments, so everybody should consider this release as an unstable one. Also, keep in mind that, I only tested `get-*` functions, which are my priorities right now. Please, fuzz it and report issues :wink: I've tried to not break all the internals, but who knows ? 

I changed the pywerview internal version to 0.3 within some files and add some dependencies too, but, because my project management skills are based on a coin flip, maybe this is not the right things to do :man_shrugging:

:sunflower:

### CODE REVIEW

**Comment by mpgn** [comment]
Hello,

Crazy work ! when merged don't forget to push it to pip so we can use it on CME :smile: 

>  (I need to find time to listen to your podcast now, haha)

Why not being my next interviewee hug hug ? :microphone: :smiley:

**Comment by the-useless-one** [comment]
Bonjour à tous !

Thank you @mpgn and @ThePirateWhoSmellsOfSunflowers for this amazing work. So glad that `pywerview` now works in Python3, and that we no longer have problems with special characters in LDAP search!

Pywerview v0.3.0 is a go, and is published on [PyPI](https://pypi.org/project/pywerview/0.3.0/).

Cheers,

Y

**Comment by mpgn** [comment]
Will test it on cme this week 👍

**Comment by mpgn** [comment]
All good on CME for me, integrated to the cme sponsorware repo and in kali in a few weeks (will be hopefully pushed to the public repo of cme after some time)

**Pull request merged**
