### PR TITLE
Added a Dockerfile for easy build from source

### PR DESCRIPTION
**Pull request by sdcampbell**
I had some trial and error when building from source so I created this Dockerfile to make it easy. All it takes to build the Docker image is `docker build -t pywerview .`

To run it: `docker run --rm -it -v /data:$(pwd) pywerview`. Any output saved to /data will land in the current working directory.

Additionally, it would greatly simplify instructions to build from source if you updated the wiki with the `RUN` line, not including the word RUN.

### CODE REVIEW

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hello,

I pushed a [Dockerfile](https://github.com/the-useless-one/pywerview/blob/develop/Dockerfile) on the develop branch. Can you test it please ?

:sunflower:

**Comment by sdcampbell** [comment]
ERROR: Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'

**Comment by sdcampbell** [comment]
I'll work with that later today and see if I can fix it.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
You need to run

```
git pull
git checkout develop
docker build -t pywerview .
```

**Comment by sdcampbell** [comment]
Yes, that error was my fault. Your Dockerfile worked perfectly.

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
No problem!
Closing the PR now.

:sunflower:

**Pull request closed without merging**
